CREATE TABLE Jurusan(
			JurusanId INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
			NamaJurusan VARCHAR(50) NOT NULL DEFAULT('')
);

ALTER TABLE Jurusan
Add Code VARCHAR(10) NOT NULL DEFAULT('');

DELETE FROM Jurusan;